### ISSUE TITLE
'WARNING: the path of the executable cannot be located!'

### ISSUE THREAD

**Issue by Night-walker** [daokoder/dao#449]
Can that warning be raised when that path actually gets required? Or not raised at all? Also, there is missing `\n` in the end.

**Comment by daokoder** [comment]
That warning should be raised as early as possible, because it is used to determine module paths. I am curious in what situation did it failed to determine the executable path?

**Comment by Night-walker** [comment]
Well, it always fails on Windows.

**Comment by daokoder** [comment]
Then it should be fixed.

**Comment by daokoder** [comment]
Fixed.

**Comment by Night-walker** [comment]
Hmm, I'm still getting the message. How is the path determined anyway?

**Comment by daokoder** [comment]
> Hmm, I'm still getting the message. How is the path determined anyway?

Simple, check absolute path, relative path in the working directory or paths in the PATH environment variable. The last one was not fixed, now done.

**Comment by dumblob** [comment]
Hm, why is the extension `.cgi` looked up as well?

**Comment by daokoder** [comment]
A residue of using Dao for CGI scripting for a particular web server long time ago (I forgot which one). I will remove that, as it is unlikely to be needed any more.

**Comment by daokoder** [comment]
Removed.

**Comment by Night-walker** [comment]
Fixed.
